services:
  pdfviewer:
    image: python:pdf
    container_name: pdfviewer
    hostname: pdf.myapps.localhost  
    networks:
      - net
    ports:
      - "4000:4000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - ./static:/app/static
      - ./app.py:/app/app.py
      - ./authapi.py:/app/authapi.py
    environment:
      - LOGIN_EXPIRY=30 #days
      - APP_ROUTE=pdf #use only when routed through nginx. 
      - CONFIG_ENV=auth-stage #change to prod   
    
    restart: unless-stopped
networks:
  net:
    driver: bridge    
    external: true
    